# Generated by Django 3.2.9 on 2021-11-29 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_usermedia'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermedia',
            name='favourite',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usermedia',
            name='watchlist',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='usermedia',
            name='watched',
            field=models.BooleanField(default=False),
        ),
    ]
