# Generated by Django 3.2.9 on 2021-11-29 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20211129_1033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermedia',
            name='favourite',
        ),
        migrations.RemoveField(
            model_name='usermedia',
            name='watched',
        ),
        migrations.RemoveField(
            model_name='usermedia',
            name='watchlist',
        ),
        migrations.AddField(
            model_name='usermedia',
            name='filter',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
